language: python

python:
   - 2.7
   - 3.6

branches:
  only:
  - main
  - development

install:
  - sudo apt-get update -y
  - sudo apt-get install -y libfftw3-dev

  # set up conda
  - wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda config --add channels conda-forge 
  - conda config --append channels pkgw-forge 

  # install with conda and pip
  - conda create -n conda pip "pycosat>=0.6.3"
  - source activate conda
  - conda install -q python=$TRAVIS_PYTHON_VERSION numpy scipy jupyter bokeh cython matplotlib numba astropy pytest setuptools coverage pyfftw
  - conda install -q python=$TRAVIS_PYTHON_VERSION pwkit casa-tools casa-python casa-data
  - python setup.py install

script:
  - pytest

notifications:
  email: false
  slack: realfastvla:ID1qIFG70HGYf3G6Y3oWoFFk
